# Generated by Django 3.2 on 2021-05-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBaseInfo',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CountryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_A', models.BooleanField(default=False)),
                ('file_B', models.BooleanField(default=False)),
                ('file_C', models.BooleanField(default=False)),
                ('file_D', models.BooleanField(default=False)),
                ('file_E', models.BooleanField(default=False)),
                ('file_F', models.BooleanField(default=False)),
                ('file_G', models.BooleanField(default=False)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countrybaseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CountyLinkDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('1', 'ANNUALLY'), ('2', 'QUARTERLY'), ('3', 'MONTHLY'), ('4', 'WEEKLY')], max_length=1)),
                ('remarks', models.CharField(max_length=100)),
                ('isMarco', models.BooleanField(default=False)),
                ('topic', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countrybaseinfo')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countryfiles')),
            ],
        ),
        migrations.CreateModel(
            name='CountryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual', to=settings.AUTH_USER_MODEL)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countrybaseinfo')),
                ('country_shadow1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow1', to=settings.AUTH_USER_MODEL)),
                ('country_shadow2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow2', to=settings.AUTH_USER_MODEL)),
                ('country_shadow3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
