# Generated by Django 3.2 on 2021-05-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryassignment',
            options={'verbose_name_plural': 'CountryAssignment(s)'},
        ),
        migrations.AlterModelOptions(
            name='countrybaseinfo',
            options={'verbose_name_plural': 'CountryBaseInfo(s)'},
        ),
        migrations.AlterModelOptions(
            name='countryfiles',
            options={'verbose_name_plural': 'CountryFiles'},
        ),
        migrations.AlterModelOptions(
            name='countylinkdirectory',
            options={'ordering': ['-country_code'], 'verbose_name_plural': 'CountyLinkDirectory(s)'},
        ),
        migrations.AddField(
            model_name='countrybaseinfo',
            name='country_section',
            field=models.CharField(choices=[('1', 'SECTION A'), ('2', 'SECTION B'), ('3', 'SECTION C')], default='1', max_length=1),
        ),
    ]
