# Generated by Django 3.2 on 2021-05-18 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0004_alter_countryfiles_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryassignment',
            name='country_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countryassignment',
            name='country_shadow1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countryassignment',
            name='country_shadow2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countryassignment',
            name='country_shadow3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow3', to=settings.AUTH_USER_MODEL),
        ),
    ]
