# Generated by Django 3.2 on 2021-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20210518_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryfiles',
            name='file_A',
        ),
        migrations.RemoveField(
            model_name='countryfiles',
            name='file_B',
        ),
        migrations.RemoveField(
            model_name='countryfiles',
            name='file_C',
        ),
        migrations.RemoveField(
            model_name='countryfiles',
            name='file_D',
        ),
        migrations.RemoveField(
            model_name='countryfiles',
            name='file_E',
        ),
        migrations.RemoveField(
            model_name='countryfiles',
            name='file_F',
        ),
        migrations.RemoveField(
            model_name='countryfiles',
            name='file_G',
        ),
        migrations.AddField(
            model_name='countryfiles',
            name='file_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1),
        ),
    ]
