# Generated by Django 3.2 on 2021-05-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20210518_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfiles',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.countrybaseinfo'),
        ),
    ]
