# Generated by Django 3.2 on 2021-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_auto_20210519_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='countylinkdirectory',
            name='column_update',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
