# Generated by Django 3.2 on 2021-05-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_countylinkdirectory_column_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualcountrylinkdirectory',
            name='year_9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_11',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_12',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_13',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_14',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_15',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_16',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_17',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_18',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_19',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_20',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_21',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_22',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_23',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_24',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthcountrylinkdirectory',
            name='month_9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_11',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_12',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_13',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_14',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quartercountrylinkdirectory',
            name='quarter_9',
            field=models.DateField(blank=True, null=True),
        ),
    ]
