# Generated by Django 3.2 on 2021-05-14 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_leaverecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leavereocrd_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
